### PR TITLE
Boar enemy fixed and in

### LINKED ISSUE #49: TODO: Add 3rd enemy type
Harry is working on the boar (3rd enemy type)

### PR DESCRIPTION
**Pull request by HarryThVu**
Bit of a difficult enemy but in

### CODE REVIEW

**Comment by n8hopp** [comment]
Any way to test this functionality? I didn't notice a scene or anything that had the boar in it; Not sure how @PennyS8's code works for spawning enemies, might be up to her to take a look and see if Boar is ready for main

**Comment by PennyS8** [comment]
I pushed a change to the branch that spawns boars in the waves

**Comment by PennyS8** [comment]
Currently the boar speed needs to be adjusted, and the walk speed is parabolic like the slime instead of linear speed like the skeleton

**Review by clarkm25 — DISMISSED** [review]
Boar needs to be nerfed (such as speed and maybe some other stuff) I belive Nate is working on this now

**Review by arcangel25 — APPROVED** [review]
:)

**Pull request merged**
