### PR TITLE
Leaderboard

### LINKED ISSUE #28: REACH: Projectile attack sprite placement
With the paladin, the projectile attacks (specifically noticed with the 'K' attack or the two swipe attacks) do not flip correctly when shooting to the left so when they leave the player, they are lower than they should be (the sprite is just being rotated instead of flipped when shooting to the left).

### LINKED ISSUE #83: REACH: Leaderboard
I can add this

### PR DESCRIPTION
**Pull request by n8hopp**
- Infinite Scaling Abilities
- XP now overflows
- XP now magnetizes to player
- Leaderboard fully working and blocked in Nux Mode, viewable from Character Select screen
- Boar drops XP value 3, green orb
- Dragon drops XP value 20, red orb
- Projectiles flip properly when facing left

### CODE REVIEW

**Comment by PennyS8** [comment]
@n8hopp there are some merge conflicts, I assume related to the de cluttering branch I merged already. Also this PR LGTM but I am unable to accept the PR, I think because @clarkm25 was requested to review.

**Review by clarkm25 — DISMISSED** [review]
I know we talked about it but I don't know if you want to implement the hiding of the key, if so we should probably do that before accepting this.

Also the projectile sprites got messed up. They work great going left now but they disappear going down and up and they are pointed left or right while going diagonally.

**Comment by PennyS8** [comment]
projectiles orientation has been corrected. still need to hide the leaderboard API key

**Comment by n8hopp** [comment]
> @n8hopp there are some merge conflicts, I assume related to the de cluttering branch I merged already. Also this PR LGTM but I am unable to accept the PR, I think because @clarkm25 was requested to review.

Aaa what

read PR descriptions please

from other PR: 
“Honestly - would prefer if you merge https://github.com/n8hopp/mageburn/pull/96 before this one; might use some stuff that would get overwritten if you pushed this one first.”

we might need to roll back and merge the other order once I add api key protection

**Comment by n8hopp** [comment]
Should be good now. Fixed some stuff and added some stuff. Look at commit details [c0845ad](https://github.com/n8hopp/mageburn/pull/96/commits/c0845adaff4a7c8d351ded41962bc3221cf023f1) and [1aada18](https://github.com/n8hopp/mageburn/pull/96/commits/1aada18c45b8721b5c02a7d3a0645f094eeca901) if interested.

**Review by PennyS8 — APPROVED** [review]
LGTM

**Pull request merged**
