### PR TITLE
Basic Nux Mode implemented

### LINKED ISSUE #46: TODO: Add Nux Mode
We need to implement an easy version of the game so that Nuxoll can play test it

### PR DESCRIPTION
**Pull request by clarkm25**
Nux Mode now sets the health to 1000 and the strength to 30

### CODE REVIEW

**Review by arcangel25 — CHANGES_REQUESTED** [review]
Immortal chicken bug-- instead of dying or tantrum it stays red and is unkillable

**Comment by clarkm25** [comment]
> Immortal chicken bug-- instead of dying or tantrum it stays red and is unkillable

Fixed in "3rd abilities working" (#68)

**Comment by PennyS8** [comment]
Rejecting the PR until the non-Nux mode (Nate mode) cannot level up by pressing override key x

**Comment by arcangel25** [comment]
Have all abilities available for level up (up and down)

**Review by arcangel25 — APPROVED** [review]

**Pull request merged**
